CREATE OR REPLACE FUNCTION F_GET_BOOKS_SOLD_BY_YEAR_AND_CATEGORY(P_CATEGORY BOOKS.CATEGORY%TYPE, P_YEAR NUMBER) RETURN NUMBER IS
    BOOKS_SOLD NUMBER;
BEGIN
    SELECT SUM(1)
    INTO BOOKS_SOLD
    FROM ORDERITEMS OI
             JOIN ORDERS O ON OI.ORDER# = O.ORDER#
             JOIN BOOKS B ON OI.ISBN = B.ISBN
    WHERE EXTRACT(YEAR FROM O.ORDERDATE) = P_YEAR
      AND UPPER(P_CATEGORY) = UPPER(B.CATEGORY);

    RETURN BOOKS_SOLD;
END;

CREATE TABLE CATEGORY_BY_YEAR

(
    YEAR     NUMBER(4),
    CATEGORY VARCHAR2(30),
    QUANTITY NUMBER

);

CREATE OR REPLACE PROCEDURE P_UPDATE_CATEGORY_BY_YEAR IS
BEGIN
    MERGE INTO CATEGORY_BY_YEAR C
    USING (SELECT F_GET_BOOKS_SOLD_BY_YEAR_AND_CATEGORY(SUB2.YEAR, SUB2.CATEGORY) AS QUANTITY, SUB2.YEAR, SUB2.CATEGORY
           FROM (SELECT DISTINCT EXTRACT(YEAR FROM O.ORDERDATE) AS YEAR, B.CATEGORY
                 FROM ORDERITEMS OI
                          JOIN ORDERS O ON OI.ORDER# = O.ORDER#
                          JOIN BOOKS B ON OI.ISBN = B.ISBN) SUB2
           ORDER BY CATEGORY, YEAR) SUB
    ON (C.YEAR = SUB.YEAR AND C.CATEGORY = SUB.CATEGORY AND C.QUANTITY = SUB.QUANTITY)
    WHEN NOT MATCHED THEN
        INSERT (YEAR, CATEGORY, QUANTITY) VALUES (SUB.YEAR, SUB.CATEGORY, SUB.QUANTITY);

END;

BEGIN
    P_UPDATE_CATEGORY_BY_YEAR;
END;