-- TWORZENIE PERSPEKTYW

CREATE OR REPLACE VIEW V_PUBLISHER AS
SELECT *
FROM PUBLISHER;

CREATE OR REPLACE VIEW V_BOOKS AS
SELECT *
FROM BOOKS;

CREATE OR REPLACE VIEW V_AUTHOR AS
SELECT *
FROM AUTHOR;

CREATE OR REPLACE VIEW V_CUSTOMERS AS
SELECT *
FROM CUSTOMERS;

CREATE OR REPLACE VIEW V_TIME AS
SELECT *
FROM D_TIME;

CREATE OR REPLACE VIEW V_SALE AS
SELECT P.PUBID,
       B.ISBN,
       C.CUSTOMER#,
       T.ID_TIME,
       A.AUTHORID,
       SUM(OI.QUANTITY)                       AS QUANTITY,
       SUM(OI.QUANTITY * (B.RETAIL - B.COST)) AS PROFIT,
       SUM(OI.QUANTITY * B.RETAIL)            AS SALE_AMOUNT
FROM PUBLISHER P
         JOIN BOOKS B ON P.PUBID = B.PUBID
         JOIN ORDERITEMS OI ON OI.ISBN = B.ISBN
         JOIN ORDERS O ON O.ORDER# = OI.ORDER#
         JOIN CUSTOMERS C ON C.CUSTOMER# = O.CUSTOMER#
         JOIN BOOKAUTHOR BA ON BA.ISBN = B.ISBN
         JOIN AUTHOR A ON A.AUTHORID = BA.AUTHORID
         JOIN D_TIME T ON T.ORDERDATE = O.ORDERDATE
GROUP BY P.PUBID,
         B.ISBN,
         C.CUSTOMER#,
         T.ID_TIME,
         A.AUTHORID;