DROP TABLE TIME_DIM CASCADE CONSTRAINTS;
CREATE TABLE TIME_DIM
(
    TIME_ID       NUMBER PRIMARY KEY,
    SELL_DATE     DATE,
    WEEK_DAY      NUMBER(1),
    IS_WEEKEND    NUMBER(1),
    WEEK_DAY_NAME VARCHAR2(32),
    MONTH_NAME    VARCHAR2(32),
    MONTH         NUMBER(2),
    YEAR          NUMBER(4)
);

DROP TABLE PRODUCTS_DIM CASCADE CONSTRAINTS;
CREATE TABLE PRODUCTS_DIM
(
    PRODUCT_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(128),
    CATEGORY_NAME VARCHAR2(64)
)

DROP TABLE LOCALIZATIONS_DIM CASCADE CONSTRAINTS;
CREATE TABLE LOCALIZATIONS_DIM
(
    LOCALIZATION_ID NUMBER PRIMARY KEY,
    COUNTRY         VARCHAR2(64),
    STATE           VARCHAR2(64),
    CITY            VARCHAR2(64)
)

-- TABELA FAKTÓW REPREZENTUJE DZIENNĄ SPRZEDAŻ PRODUKTU W DANEJ LOKALIZACJI
DROP TABLE SALES_FACT CASCADE CONSTRAINTS;
CREATE TABLE SALES_FACT
(
    TIME_ID     NUMBER REFERENCES TIME_DIM(TIME_ID),
    PRODUCT_ID  NUMBER REFERENCES PRODUCTS_DIM(PRODUCT_ID),
    LOCALIZATION_ID NUMBER REFERENCES LOCALIZATIONS_DIM(LOCALIZATION_ID),
    VALUE_M     NUMBER(14, 6),
    PROFIT_M    NUMBER(14, 6),
    PRIMARY KEY (TIME_ID, PRODUCT_ID, LOCALIZATION_ID)
)

DROP SEQUENCE S_TIME_DIM;
CREATE SEQUENCE S_TIME_DIM;
CREATE OR REPLACE TRIGGER T_SET_TIME_DIM_ID
    BEFORE INSERT
    ON TIME_DIM
    FOR EACH ROW
BEGIN
    :NEW.TIME_ID := S_TIME_DIM.NEXTVAL;
END;

DROP SEQUENCE  S_LOCALIZATIONS_DIM;
CREATE SEQUENCE S_LOCALIZATIONS_DIM;
CREATE OR REPLACE TRIGGER T_SET_LOCALIZATION_DIM_ID
    BEFORE INSERT
    ON LOCALIZATIONS_DIM
    FOR EACH ROW
BEGIN
    :NEW.LOCALIZATION_ID := S_LOCALIZATIONS_DIM.NEXTVAL;
END;

DROP SEQUENCE S_PRODUCTS_DIM;
CREATE SEQUENCE S_PRODUCTS_DIM;
CREATE OR REPLACE TRIGGER T_SET_PRODUCTS_DIM_ID
    BEFORE INSERT
    ON PRODUCTS_DIM
    FOR EACH ROW
BEGIN
    :NEW.PRODUCT_ID := S_PRODUCTS_DIM.NEXTVAL;
END;

CREATE OR REPLACE PROCEDURE P_INIT_TIME_DIM IS
BEGIN
    MERGE INTO TIME_DIM T
    USING (SELECT O.ORDER_DATE

        FROM ORDERS O
END;