DROP TABLE ZIP CASCADE CONSTRAINTS;
CREATE TABLE ZIP
(
    ID_ZIP   NUMBER(5) PRIMARY KEY,
    ZIP_CODE VARCHAR2(5),
    STATE    VARCHAR2(2)
);

DROP TABLE TIME CASCADE CONSTRAINTS;
CREATE TABLE TIME
(
    ID_TIME NUMBER(4) PRIMARY KEY,
    MONTH   NUMBER(2),
    YEAR    NUMBER(4)
);

DROP TABLE SALE CASCADE CONSTRAINTS;
CREATE TABLE SALE
(
    ID_SALE     NUMBER PRIMARY KEY,
    ID_ZIP      NUMBER(5) REFERENCES ZIP (ID_ZIP),
    ID_TIME     NUMBER(4) REFERENCES TIME (ID_TIME),
    SALE_AMOUNT NUMBER
);

DROP TABLE PROFIT_BY_STATE CASCADE CONSTRAINTS;
CREATE TABLE PROFIT_BY_STATE
(
    STATE  VARCHAR2(2) PRIMARY KEY,
    PROFIT NUMBER
);

CREATE SEQUENCE S_ZIP;
CREATE SEQUENCE S_TIME;
CREATE SEQUENCE S_SALE;

DROP TRIGGER T_SET_ID_ZIP;
CREATE
    OR REPLACE TRIGGER T_SET_ID_ZIP
    BEFORE INSERT
    ON ZIP
    FOR EACH ROW
BEGIN
    :NEW.ID_ZIP := S_ZIP.NEXTVAL;
END;
/

DROP TRIGGER T_SET_ID_TIME;
CREATE
    OR REPLACE TRIGGER T_SET_ID_TIME
    BEFORE INSERT
    ON TIME
    FOR EACH ROW
BEGIN
    :NEW.ID_TIME := S_TIME.NEXTVAL;
END;
/

DROP TRIGGER T_SET_ID_SALE;
CREATE
    OR REPLACE TRIGGER T_SET_ID_SALE
    BEFORE INSERT
    ON SALE
    FOR EACH ROW
BEGIN
    :NEW.ID_SALE := S_SALE.NEXTVAL;
END;
/

COMMIT;