--ZAD2

DROP TABLE LOCALIZATIONS CASCADE CONSTRAINTS;
CREATE TABLE LOCALIZATIONS
(
    LOCALIZATION_ID NUMBER PRIMARY KEY,
    COUNTRY         VARCHAR2(64),
    STATE           VARCHAR2(64),
    CITY            VARCHAR2(64)
);

DROP TABLE CUSTOMERS CASCADE CONSTRAINTS;
CREATE TABLE CUSTOMERS
(
    CUSTOMER_ID NUMBER PRIMARY KEY,
    EMAIL       VARCHAR2(64)
);

DROP TABLE CATEGORIES CASCADE CONSTRAINTS;
CREATE TABLE CATEGORIES
(
    CATEGORY_ID   NUMBER PRIMARY KEY,
    CATEGORY_NAME VARCHAR2(64)
);

DROP TABLE PRODUCTS CASCADE CONSTRAINTS;
CREATE TABLE PRODUCTS
(
    PRODUCT_ID   NUMBER PRIMARY KEY,
    PRODUCT_NAME VARCHAR2(128),
    CATEGORY_ID  NUMBER REFERENCES CATEGORIES (CATEGORY_ID)
);

DROP TABLE ORDERS CASCADE CONSTRAINTS;
CREATE TABLE ORDERS
(
    ORDER_ID     NUMBER PRIMARY KEY,
    ORDER_NUMBER VARCHAR2(15),
    ORDER_DATE   DATE,
    SHIP_DATE    DATE,
    CUSTOMER_ID REFERENCES CUSTOMERS (CUSTOMER_ID),
    LOCALIZATION_ID NUMBER REFERENCES LOCALIZATIONS (LOCALIZATION_ID)
);

DROP TABLE ORDERPRODUCTS CASCADE CONSTRAINTS;
CREATE TABLE ORDERPRODUCTS
(
    ORDERPRODUCT_ID NUMBER PRIMARY KEY,
    ORDER_ID   NUMBER REFERENCES ORDERS (ORDER_ID),
    PRODUCT_ID NUMBER REFERENCES PRODUCTS (PRODUCT_ID),
    QUANTITY   NUMBER(10),
    PROFIT     NUMBER(10, 2),
    SALES      NUMBER(10, 2)
);

-- ZAD3

DROP SEQUENCE S_CUSTOMERS;
DROP SEQUENCE S_LOCALIZATIONS;
DROP SEQUENCE S_CATEGORIES;
DROP SEQUENCE S_PRODUCTS;
DROP SEQUENCE S_ORDERS;
DROP SEQUENCE S_ORDERPRODUCTS;


CREATE SEQUENCE S_CUSTOMERS;
CREATE SEQUENCE S_LOCALIZATIONS;
CREATE SEQUENCE S_CATEGORIES;
CREATE SEQUENCE S_PRODUCTS;
CREATE SEQUENCE S_ORDERS;
CREATE SEQUENCE S_ORDERPRODUCTS;

CREATE OR REPLACE TRIGGER T_SET_CUSTOMER_ID
    BEFORE INSERT
    ON CUSTOMERS
    FOR EACH ROW
BEGIN
    :NEW.CUSTOMER_ID := S_CUSTOMERS.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER T_SET_LOCALIZATION_ID
    BEFORE INSERT
    ON LOCALIZATIONS
    FOR EACH ROW
BEGIN
    :NEW.LOCALIZATION_ID := S_LOCALIZATIONS.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER T_SET_CATEGORY_ID
    BEFORE INSERT
    ON CATEGORIES
    FOR EACH ROW
BEGIN
    :NEW.CATEGORY_ID := S_CATEGORIES.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER T_SET_PRODUCT_ID
    BEFORE INSERT
    ON PRODUCTS
    FOR EACH ROW
BEGIN
    :NEW.PRODUCT_ID := S_PRODUCTS.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER T_SET_ORDER_ID
    BEFORE INSERT
    ON ORDERS
    FOR EACH ROW
BEGIN
    :NEW.ORDER_ID := S_ORDERS.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER T_SET_ORDERPRODUCT_ID
    BEFORE INSERT
    ON ORDERPRODUCTS
    FOR EACH ROW
BEGIN
    :NEW.ORDERPRODUCT_ID := S_ORDERPRODUCTS.NEXTVAL;
END;
/

--INDEXES NEED FOR FASTER QUERIES
CREATE INDEX IDX_PRODUCTS_PRODUCT_NAME ON PRODUCTS (PRODUCT_NAME);
CREATE INDEX IDX_ORDERS_ORDER_NUMBER ON ORDERS (ORDER_NUMBER);